### ISSUE TITLE
prerequisites or instructions need update

### ISSUE THREAD

**Issue by kikiya** [cloudstateio/samples-js-shoppingcart#16]
the instructions as listed require `jq` and also `watch`

by default: `zsh: command not found: watch` 

we may not need the bit which lists `jq` since successful project creation returns the command needed to set the project. 

i.e. ` csctl projects new sample-shopping-cart "Shopping Cart Sample" --context lbcs.dev
Created project edb3cbd5-239d-4c5f-ba8c-5a1c32fc0b6b.
To make this the currently active project, run: 'csctl config set project edb3cbd5-239d-4c5f-ba8c-5a1c32fc0b6b'`

**Comment by vkorenev** [comment]
I have already removed `jq` usage (see #11 and #13). `watch` needs to be removed as well.
